export const resumeThemes = [
  {
    id: 'slate',
    label: 'Slate',
    accent: 'bg-slate-900',
    accentSoft: 'bg-slate-100',
    accentText: 'text-slate-900',
    section: 'text-slate-500',
    chip: 'bg-slate-100 text-slate-700',
    border: 'border-slate-200',
    preview: ['#0f172a', '#334155', '#94a3b8', '#e2e8f0'],
  },
  {
    id: 'ocean',
    label: 'Ocean',
    accent: 'bg-sky-700',
    accentSoft: 'bg-sky-100',
    accentText: 'text-sky-900',
    section: 'text-sky-700',
    chip: 'bg-sky-50 text-sky-800',
    border: 'border-sky-200',
    preview: ['#0369a1', '#0ea5e9', '#7dd3fc', '#e0f2fe'],
  },
  {
    id: 'forest',
    label: 'Forest',
    accent: 'bg-emerald-700',
    accentSoft: 'bg-emerald-100',
    accentText: 'text-emerald-900',
    section: 'text-emerald-700',
    chip: 'bg-emerald-50 text-emerald-800',
    border: 'border-emerald-200',
    preview: ['#047857', '#10b981', '#6ee7b7', '#d1fae5'],
  },
  {
    id: 'sunrise',
    label: 'Sunrise',
    accent: 'bg-amber-600',
    accentSoft: 'bg-amber-100',
    accentText: 'text-amber-900',
    section: 'text-amber-700',
    chip: 'bg-amber-50 text-amber-800',
    border: 'border-amber-200',
    preview: ['#d97706', '#f59e0b', '#fcd34d', '#fef3c7'],
  },
  {
    id: 'rose',
    label: 'Rose',
    accent: 'bg-rose-700',
    accentSoft: 'bg-rose-100',
    accentText: 'text-rose-900',
    section: 'text-rose-700',
    chip: 'bg-rose-50 text-rose-800',
    border: 'border-rose-200',
    preview: ['#be123c', '#f43f5e', '#fda4af', '#ffe4e6'],
  },
  {
    id: 'violet',
    label: 'Violet',
    accent: 'bg-violet-700',
    accentSoft: 'bg-violet-100',
    accentText: 'text-violet-900',
    section: 'text-violet-700',
    chip: 'bg-violet-50 text-violet-800',
    border: 'border-violet-200',
    preview: ['#6d28d9', '#8b5cf6', '#c4b5fd', '#ede9fe'],
  },
  {
    id: 'teal',
    label: 'Teal',
    accent: 'bg-teal-700',
    accentSoft: 'bg-teal-50',
    accentText: 'text-teal-900',
    section: 'text-teal-700',
    chip: 'bg-teal-50 text-teal-800',
    border: 'border-teal-200',
    preview: ['#0f766e', '#14b8a6', '#99f6e4', '#ccfbf1'],
  },
  {
    id: 'gold',
    label: 'Amber',
    accent: 'bg-amber-700',
    accentSoft: 'bg-amber-50',
    accentText: 'text-amber-900',
    section: 'text-amber-700',
    chip: 'bg-amber-50 text-amber-800',
    border: 'border-amber-200',
    preview: ['#b45309', '#f59e0b', '#fde68a', '#fef3c7'],
  },
  {
    id: 'grape',
    label: 'Grape',
    accent: 'bg-fuchsia-700',
    accentSoft: 'bg-fuchsia-50',
    accentText: 'text-fuchsia-900',
    section: 'text-fuchsia-700',
    chip: 'bg-fuchsia-50 text-fuchsia-800',
    border: 'border-fuchsia-200',
    preview: ['#a21caf', '#d946ef', '#f5d0fe', '#fae8ff'],
  },
]

export const defaultResumeTheme = resumeThemes[0]

export const getResumeTheme = (themeId) =>
  resumeThemes.find((theme) => theme.id === themeId) ?? defaultResumeTheme